Portfolio page storage
ijeomaese/Portfolio-Page pull request #19
Opened 2022-04-14 12:28 UTC by ijeomaodinko

This file contains the files for storage on the browser in the following;
The index.html file, style.css file, and main.js file. 
The lineters.

2022-04-14 12:39 UTC, BenMukebo approved these changes

2022-04-14 12:45 UTC, BenMukebo reviewed
## STATUS: INVALID ❌ 

Hi @ijeomaodinko,

## Invalid Code Review Request 

I can't miss felicitating your efforts and energy While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

- [ ] You have submitted a project, that doesn't have commits from all members in your pair programming group. Kindly note that this is a pair programming activity and all the members should commit to the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@BenMukebo) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit.

2022-04-15 08:17 UTC, Deepakdanger requested changes
**Hi @Team**, 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlight :100: 
- No linter error :+1: 
- Local storage is working fine :+1: 

## Required Changes ♻️
- [ ] In the Readme file, Kindly include all the author's detail.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-15 08:53 UTC, Kingstalux approved these changes
Hi @team,
# Status: Approved ✔️✔️✔️
  
![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/163549346-c164f6e5-2834-40a7-8510-893479cb166c.gif)

## Highlights
✅ Data is preserved in the browser 🔥 
✅ Linters are passing 👏 
✅ Good commit messages 

Good job implementing the required changes 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-28 01:00 UTC, merged