Porfolio page mobile events
ijeomaese/Portfolio-Page pull request #9
Opened 2022-04-05 11:34 UTC by ijeomaodinko

This file contains the following files:
The inex.html file, style.css, and main.js files.
It contains linters files.

2022-04-05 11:49 UTC, keroloussamy requested changes
Hi @ijeomaodinko, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Optional suggestions
_Check the comments under the review._

- [ ] x

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-05 11:49 UTC, keroloussamy commented on style.css
> +}
- [ ] Your menu is working perfectly, just one thing is you have to make your desktop version match the figma design. Kindly make the navigations items appear on the desktop version, you have to change the `color: #fff;` to make them appear.

Your design
![image](https://user-images.githubusercontent.com/35535130/161746466-f1904dca-b9ee-4c24-ba48-321435d7741f.png)

Figma design
![image](https://user-images.githubusercontent.com/35535130/161746700-df308015-bbca-4c65-b470-c60fba5b5bb7.png)

2022-04-05 11:49 UTC, keroloussamy commented on .eslintrc.json
> +  }
- [ ] Great work adding linters, just one thing to make them run on GitHub is you have to update your `linters.yml` with this [linters.yml](https://github.com/microverseinc/linters-config/blob/master/html-css-js/.github/workflows/linters.yml), After that chack that your linters are passing.

2022-04-05 13:04 UTC, ShadyShawkat approved these changes
## Hi @ijeomaodinko, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-07 14:23 UTC, merged

2022-04-11 08:21 UTC, brytebee commented
Hi, @ijeomaodinko👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Status: Invalid Code Review Request

![](https://media.giphy.com/media/OQeKGexhYKVjLaSzPd/giphy.gif)

**_You have submitted a project, that has been merged already. Kindly confirm and submit a branch with the correct work for this milestone._**

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._